# Generated by Django 3.2.5 on 2021-11-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeAnxiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.BigIntegerField()),
                ('Underfive', models.FloatField(null=True)),
                ('FiveToFourteen', models.FloatField(null=True)),
                ('FifteenToFourtyNine', models.FloatField(null=True)),
                ('FiftyToSixtynine', models.FloatField(null=True)),
                ('Overseventy', models.FloatField(null=True)),
                ('AllAges', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genderanxiaty',
            name='Total_Percentage',
            field=models.FloatField(null=True),
        ),
    ]
